"""Unimodular invariance stress tests.

These tests are intended to catch the specific "silent failure" mode where a
basis-dependent quantity is used for pruning/scoring *before* reduction to a
GL(2,Z)-invariant canonical form.

Practical interpretation
-----------------------
For any unimodular integer matrix U (det(U)=±1), the 2D lattice generated by a
basis S and the lattice generated by S@U are identical (they are different
choices of primitive vectors for the same lattice). A correct canonicalization
pipeline must therefore satisfy:

- Reduction/canonicalization:   reduce(S) == reduce(S@U)  (up to numerical tol)
- Any *canonical* mismatch/strain metrics computed *after reduction* must be
  invariant under S -> S@U.

These tests deliberately exercise both:
- the canonical Gauss 2D reduction in ``calm.symmetry.reduction``
- the two metric families exposed to users:
  - :class:`~calm.interface.types.AffineInvariantStrain2D`
  - :class:`~calm.interface.types.ZMStrain2D`
"""

from __future__ import annotations

import itertools

import numpy as np


def _det2(M: np.ndarray) -> int:
    M = np.asarray(M, dtype=int)
    return int(M[0, 0] * M[1, 1] - M[0, 1] * M[1, 0])


def _unimodular_samples(limit: int = 2) -> list[np.ndarray]:
    """Generate a deterministic set of small GL(2,Z) matrices.

    We keep the entry range small so the test suite remains fast, but wide
    enough to include swaps, sign flips, and "shear" basis changes.
    """

    mats: list[np.ndarray] = []
    rng = range(-limit, limit + 1)
    for a, b, c, d in itertools.product(rng, repeat=4):
        U = np.asarray([[a, b], [c, d]], dtype=int)
        if _det2(U) in (1, -1):
            mats.append(U)

    # Deterministic ordering improves debuggability.
    mats.sort(key=lambda M: (int(np.sum(np.abs(M))), int(M[0, 0]), int(M[0, 1]), int(M[1, 0]), int(M[1, 1])))
    return mats


def test_canonical_gauss_reduce_2d_is_invariant_to_unimodular_basis_relabelings() -> None:
    """Reduction should not depend on the input primitive basis choice."""

    from calm.symmetry.reduction import canonical_gauss_reduce_2d

    # A generic (non-degenerate) 2D basis (columns are basis vectors)
    S = np.asarray([[2.0, 0.7], [0.1, 1.9]], dtype=float)

    S0, _, _ = canonical_gauss_reduce_2d(S, tol=1e-12, warn_on_handedness_repair=False)
    G0 = S0.T @ S0

    for U in _unimodular_samples():
        S_u = S @ U
        S1, _, _ = canonical_gauss_reduce_2d(S_u, tol=1e-12, warn_on_handedness_repair=False)
        G1 = S1.T @ S1

        assert np.allclose(G1, G0, atol=1e-10, rtol=0.0)


def test_canonicalized_metrics_are_invariant_to_independent_unimodular_relabelings() -> None:
    """AffineInvariantStrain2D and ZMStrain2D must be invariant after reduction."""

    from calm.interface.types import AffineInvariantStrain2D, ZMStrain2D
    from calm.symmetry.reduction import canonical_gauss_reduce_2d

    # Two unrelated primitive bases (columns are basis vectors)
    A = np.asarray([[2.0, 0.7], [0.1, 1.9]], dtype=float)
    B = np.asarray([[1.6, -0.3], [0.2, 1.4]], dtype=float)

    A0, _, _ = canonical_gauss_reduce_2d(A, tol=1e-12, warn_on_handedness_repair=False)
    B0, _, _ = canonical_gauss_reduce_2d(B, tol=1e-12, warn_on_handedness_repair=False)

    G_A0 = A0.T @ A0
    G_B0 = B0.T @ B0

    a0 = AffineInvariantStrain2D.from_grams(G_A0, G_B0)
    z0 = ZMStrain2D.from_bases(A0, B0)

    for U in _unimodular_samples():
        # Relabel A only
        A_u, _, _ = canonical_gauss_reduce_2d(A @ U, tol=1e-12, warn_on_handedness_repair=False)
        G_Au = A_u.T @ A_u

        a1 = AffineInvariantStrain2D.from_grams(G_Au, G_B0)
        z1 = ZMStrain2D.from_bases(A_u, B0)

        assert np.isclose(a1.d_cell, a0.d_cell, atol=1e-10, rtol=0.0)
        assert np.isclose(a1.d_area, a0.d_area, atol=1e-10, rtol=0.0)
        assert np.isclose(a1.d_shape, a0.d_shape, atol=1e-10, rtol=0.0)
        assert np.isclose(a1.max_abs_principal_strain, a0.max_abs_principal_strain, atol=1e-10, rtol=0.0)

        assert np.isclose(z1.rel_da, z0.rel_da, atol=1e-10, rtol=0.0)
        assert np.isclose(z1.rel_db, z0.rel_db, atol=1e-10, rtol=0.0)
        assert np.isclose(z1.d_gamma_deg, z0.d_gamma_deg, atol=1e-10, rtol=0.0)
        assert np.isclose(z1.rel_dgamma, z0.rel_dgamma, atol=1e-10, rtol=0.0)

        # Relabel B only
        B_u, _, _ = canonical_gauss_reduce_2d(B @ U, tol=1e-12, warn_on_handedness_repair=False)
        G_Bu = B_u.T @ B_u

        a2 = AffineInvariantStrain2D.from_grams(G_A0, G_Bu)
        z2 = ZMStrain2D.from_bases(A0, B_u)

        assert np.isclose(a2.d_cell, a0.d_cell, atol=1e-10, rtol=0.0)
        assert np.isclose(a2.d_area, a0.d_area, atol=1e-10, rtol=0.0)
        assert np.isclose(a2.d_shape, a0.d_shape, atol=1e-10, rtol=0.0)
        assert np.isclose(a2.max_abs_principal_strain, a0.max_abs_principal_strain, atol=1e-10, rtol=0.0)

        assert np.isclose(z2.rel_da, z0.rel_da, atol=1e-10, rtol=0.0)
        assert np.isclose(z2.rel_db, z0.rel_db, atol=1e-10, rtol=0.0)
        assert np.isclose(z2.d_gamma_deg, z0.d_gamma_deg, atol=1e-10, rtol=0.0)
        assert np.isclose(z2.rel_dgamma, z0.rel_dgamma, atol=1e-10, rtol=0.0)
