"""Matplotlib plotting helpers for two-dimensional lattices."""

from __future__ import annotations

from dataclasses import dataclass
from collections.abc import Sequence
from typing import Any

import numpy as np
from matplotlib.axes import Axes
from matplotlib.collections import PathCollection
from matplotlib.colors import to_rgba
from matplotlib.lines import AxLine
from matplotlib.patches import Polygon
from numpy.typing import ArrayLike

from .geometry import (
    as_basis,
    as_index_range,
    as_point,
    cell_centroid,
    cell_vertices,
    lattice_sites,
)


@dataclass(frozen=True)
class LatticeArtists:
    """Artists created by :func:`plot_lattice`."""

    grid_lines: tuple[AxLine, ...]
    sites: PathCollection | None
    cell: Polygon | None


def plot_grid(
    ax: Axes,
    basis: ArrayLike,
    *,
    i_range: Sequence[int] = (-4, 4),
    j_range: Sequence[int] = (-4, 4),
    origin: ArrayLike = (0.0, 0.0),
    color: Any = "k",
    linewidth: float = 1.0,
    alpha: float = 1.0,
    linestyle: str = "-",
    zorder: float = 1.0,
) -> tuple[AxLine, ...]:
    """Plot the two families of infinite grid lines defined by a basis."""
    basis_array = as_basis(basis, name="grid_basis")
    origin_array = as_point(origin, name="origin")
    i_min, i_max = as_index_range(i_range, name="i_range")
    j_min, j_max = as_index_range(j_range, name="j_range")

    g1 = basis_array[:, 0]
    g2 = basis_array[:, 1]
    lines: list[AxLine] = []

    for j in range(j_min, j_max + 1):
        point = origin_array + j * g2
        lines.append(
            ax.axline(
                point,
                point + g1,
                color=color,
                linewidth=linewidth,
                alpha=alpha,
                linestyle=linestyle,
                zorder=zorder,
            )
        )

    for i in range(i_min, i_max + 1):
        point = origin_array + i * g1
        lines.append(
            ax.axline(
                point,
                point + g2,
                color=color,
                linewidth=linewidth,
                alpha=alpha,
                linestyle=linestyle,
                zorder=zorder,
            )
        )

    return tuple(lines)


def plot_sites(
    ax: Axes,
    basis: ArrayLike,
    *,
    i_range: Sequence[int] = (-8, 8),
    j_range: Sequence[int] = (-8, 8),
    origin: ArrayLike = (0.0, 0.0),
    color: Any = "k",
    size: float = 25.0,
    marker: Any = "o",
    edgecolor: Any = "k",
    linewidth: float = 0.5,
    alpha: float = 1.0,
    zorder: float = 3.0,
) -> PathCollection:
    """Plot lattice sites generated by a basis."""
    sites = lattice_sites(
        basis,
        i_range=i_range,
        j_range=j_range,
        origin=origin,
    )

    return ax.scatter(
        sites[:, 0],
        sites[:, 1],
        s=size,
        marker=marker,
        facecolors=color,
        edgecolors=edgecolor,
        linewidths=linewidth,
        alpha=alpha,
        zorder=zorder,
    )


def plot_cell(
    ax: Axes,
    basis: ArrayLike,
    *,
    origin: ArrayLike = (0.0, 0.0),
    cell_index: Sequence[int] = (0, 0),
    color: Any = "k",
    fill_alpha: float = 0.20,
    linewidth: float = 1.5,
    linestyle: str = "-",
    zorder: float = 2.0,
) -> Polygon:
    """Plot an indexed basis-cell parallelogram."""
    vertices = cell_vertices(
        basis,
        origin=origin,
        cell_index=cell_index,
    )
    patch = Polygon(
        vertices,
        closed=True,
        facecolor=to_rgba(color, fill_alpha),
        edgecolor=color,
        linewidth=linewidth,
        linestyle=linestyle,
        zorder=zorder,
    )
    ax.add_patch(patch)
    return patch


def plot_lattice(
    ax: Axes,
    *,
    grid_basis: ArrayLike,
    site_basis: ArrayLike | None = None,
    cell_basis: ArrayLike | None = None,
    grid_i_range: Sequence[int] = (-4, 4),
    grid_j_range: Sequence[int] = (-4, 4),
    site_i_range: Sequence[int] = (-8, 8),
    site_j_range: Sequence[int] = (-8, 8),
    origin: ArrayLike = (0.0, 0.0),
    cell_index: Sequence[int] = (0, 0),
    color: Any = "k",
    show_grid: bool = True,
    show_sites: bool = True,
    show_cell: bool = True,
    grid_linewidth: float = 1.0,
    grid_alpha: float = 1.0,
    grid_linestyle: str = "-",
    site_size: float = 25.0,
    site_marker: Any = "o",
    site_edgecolor: Any = "k",
    site_linewidth: float = 0.5,
    site_alpha: float = 1.0,
    fill_alpha: float = 0.20,
    cell_linewidth: float = 1.5,
    cell_linestyle: str = "-",
) -> LatticeArtists:
    """Plot a grid, lattice sites, and a highlighted cell independently.

    ``grid_basis`` controls the plotted line directions and spacing.
    ``site_basis`` controls the lattice-site positions. If omitted, it defaults
    to ``grid_basis``. ``cell_basis`` controls the highlighted cell and also
    defaults to ``grid_basis``.

    A common supercell use is therefore::

        plot_lattice(
            ax,
            grid_basis=supercell_basis,
            site_basis=primitive_basis,
            cell_basis=supercell_basis,
        )
    """
    grid_basis_array = as_basis(grid_basis, name="grid_basis")
    site_basis_array = (
        grid_basis_array
        if site_basis is None
        else as_basis(site_basis, name="site_basis")
    )
    cell_basis_array = (
        grid_basis_array
        if cell_basis is None
        else as_basis(cell_basis, name="cell_basis")
    )

    grid_lines: tuple[AxLine, ...] = ()
    sites: PathCollection | None = None
    cell: Polygon | None = None

    if show_grid:
        grid_lines = plot_grid(
            ax,
            grid_basis_array,
            i_range=grid_i_range,
            j_range=grid_j_range,
            origin=origin,
            color=color,
            linewidth=grid_linewidth,
            alpha=grid_alpha,
            linestyle=grid_linestyle,
        )

    if show_cell:
        cell = plot_cell(
            ax,
            cell_basis_array,
            origin=origin,
            cell_index=cell_index,
            color=color,
            fill_alpha=fill_alpha,
            linewidth=cell_linewidth,
            linestyle=cell_linestyle,
        )

    if show_sites:
        sites = plot_sites(
            ax,
            site_basis_array,
            i_range=site_i_range,
            j_range=site_j_range,
            origin=origin,
            color=color,
            size=site_size,
            marker=site_marker,
            edgecolor=site_edgecolor,
            linewidth=site_linewidth,
            alpha=site_alpha,
        )

    return LatticeArtists(
        grid_lines=grid_lines,
        sites=sites,
        cell=cell,
    )


def center_on_cell(
    ax: Axes,
    basis: ArrayLike,
    *,
    origin: ArrayLike = (0.0, 0.0),
    cell_index: Sequence[int] = (0, 0),
    half_width: float | Sequence[float] = 2.0,
    equal_aspect: bool = True,
) -> np.ndarray:
    """Center the viewport on the centroid of an indexed basis cell.

    ``half_width`` may be a scalar for a square viewport or ``(x, y)`` for
    independent horizontal and vertical half-widths. This function changes
    only the viewport; it never translates plotted lattices.
    """
    center = cell_centroid(
        basis,
        origin=origin,
        cell_index=cell_index,
    )
    widths = np.asarray(half_width, dtype=float)

    if widths.ndim == 0:
        widths = np.repeat(widths, 2)

    if widths.shape != (2,):
        raise ValueError(
            "half_width must be a scalar or a two-component sequence."
        )

    if not np.all(np.isfinite(widths)) or np.any(widths <= 0.0):
        raise ValueError("half_width values must be finite and positive.")

    ax.set_xlim(center[0] - widths[0], center[0] + widths[0])
    ax.set_ylim(center[1] - widths[1], center[1] + widths[1])

    if equal_aspect:
        ax.set_aspect("equal", adjustable="box")

    return center
