"""Dependency-light CALM stable project storage contract."""

CURRENT_SCHEMA_VERSION = "v2.0.0"
PROJECT_RELEASE_STAGE = "stable"
PROJECT_COMPATIBILITY_POLICY = "exact_current_regeneration_only"
AUTOMATIC_PROJECT_MIGRATION_SUPPORTED = False
IN_PLACE_PROJECT_REPAIR_SUPPORTED = False

__all__ = [
    "AUTOMATIC_PROJECT_MIGRATION_SUPPORTED",
    "CURRENT_SCHEMA_VERSION",
    "IN_PLACE_PROJECT_REPAIR_SUPPORTED",
    "PROJECT_COMPATIBILITY_POLICY",
    "PROJECT_RELEASE_STAGE",
]
